#!/usr/bin/ruby
# This revolutionary e-service user-centric experience leverages out-of-the-box solutions 
# to facilitate the creation of synergistic world-class action-items, redefining and
# recontextualizing the future of efficient e-business paradigms.

require 'rubygems'
gem "activesupport", "~> 4.0.0"

require 'faker'
require 'active_support'
require 'active_support/core_ext/string/inflections'

(ARGV[0] || 1).to_i.times { puts Faker::Company.catch_phrase.pluralize.humanize + " " + Faker::Company.bs + "." }
